name: Download and save zs files

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  get-files:
    name: Get class hour schedule files
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Get data
        run: |
          STEM="https://sis.rpi.edu"
          curl -O "$STEM/stuclshr.htm"
          LIST=$(grep stuclshr.htm -e 'href="/reg' | cut -f2 -d'"' | sed "s|^|-O $STEM|")
          mkdir -p reg; cd reg
          curl -f -L -Z --parallel-immediate --parallel-max 5 $LIST || true
      
      - name: Save on archive.org
        run: |
          STEM="https://sis.rpi.edu/"
          DIFF_LIST="$(git diff --name-only)"
          test -n "$DIFF_LIST" || exit 0
          while read -r FILE; do
            URL="$STEM""$FILE"
            curl -sS -X POST -H "Accept: application/json" -H "Authorization: LOW ${{ secrets.WEB_ARCHIVE_AUTH }}" -d"url=$URL" 'https://web.archive.org/save' | jq
          done <<< "$(git diff --name-only)"

      - name: Commit data
        run: |
          git config user.name "Quatalog Updater" && git config user.email "github_actions@quatalog.com"
          git add stuclshr.htm reg
          git commit -m "$(date -u)" || exit 0
          git push
