name: Download and save zs files

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  get-files:
    name: Get class hour schedule files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get data
        run: |
          STEM="https://sis.rpi.edu"
          curl -O "$STEM/stuclshr.htm"
          LIST=$(grep stuclshr.htm -e 'href="/reg' | cut -f2 -d'"' | sed "s|^|-O $STEM|")
          cd reg
          curl -Z --parallel-immediate --parallel-max 5 $LIST
      
      - name: Commit data
        run: |
          git commit -a -m "$(date -u)" || exit 0
          git push
